name: Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test init script
      run: |
        ./main.sh -i

  build-windows:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install gettext
       run: |
        choco feature enable -n=allowGlobalConfirmation
        choco install gettext
        gettext --version
    - name: Test init script
      run: |
        .\main.bat -i