name: Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Test init script
      run: |
        ./main.sh -i

  build-windows:

    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download and install gettext
      run: |
        curl -L -o gettext.zip https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.22.3/gettext-0.22.3-iconv-1.17-static-win64.zip
        unzip gettext.zip -d gettext
        echo ::add-path::%cd%\\gettext-tools >> $env:GITHUB_ENV
        gettext --version
    - name: Test init script
      run: |
        .\main.bat -i
    - name: Run interactive session
      if: failure()
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: "Admin#1234" # You can also put the password in secrets as you wish.
      #foreground: false
